<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ApplicationTitle>Shiny Sample</ApplicationTitle>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Platform.Maui.Linux.Gtk4"/>
        <PackageReference Include="Platform.Maui.Linux.Gtk4.Essentials"/>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Shiny.Maui.TableView"/>
        <PackageReference Include="Shiny.Maui.Shell"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Shiny.Core\Shiny.Core.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.BluetoothLE.Linux\Shiny.BluetoothLE.Linux.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.BluetoothLE.Hosting.Linux\Shiny.BluetoothLE.Hosting.Linux.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Support.DeviceMonitoring\Shiny.Support.DeviceMonitoring.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Support.DeviceMonitoring.Linux\Shiny.Support.DeviceMonitoring.Linux.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Notifications.Linux\Shiny.Notifications.Linux.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Jobs\Shiny.Jobs.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Net.Http\Shiny.Net.Http.csproj"/>
    </ItemGroup>
</Project>
