using System;
using System.Linq;
using FluentAssertions;
using Xunit;
using Xunit.Abstractions;


namespace Shiny.Generators.Tests
{
    public class AndroidApplicationSourceGeneratorTests : AbstractSourceGeneratorTests<AndroidApplicationSourceGenerator>
    {
        public AndroidApplicationSourceGeneratorTests(ITestOutputHelper output) : base(output, "Mono.Android", "Shiny", "Shiny.Core") {}


        [Fact]
        public void IsAutoGeneratedStartupRegistered()
        {
            this.Generator.AddSource("[assembly: Shiny.ShinyApplicationAttribute]");
            this.RunGenerator();
            this.Compilation.SyntaxTrees.Count().Should().Be(3);
            this.Compilation.AssertContent("this.ShinyOnCreate(new AppShinyStartup());", "Registration not found");
        }


        [Fact]
        public void XamarinEssentialsRegistered()
        {
            this.Generator.AddSource("[assembly: Shiny.ShinyApplicationAttribute]");
            this.Generator.AddReference("Xamarin.Essentials");
            this.RunGenerator();
            this.Compilation.AssertContent("global::Xamarin.Essentials.Platform.Init(this);");
        }
    }
}
