using System;
using System.Linq;
using FluentAssertions;
using Xunit;
using Xunit.Abstractions;


namespace Shiny.Generators.Tests
{
    public class AndroidApplicationSourceGeneratorTests : AbstractSourceGeneratorTests<AndroidApplicationSourceGenerator>
    {
        public AndroidApplicationSourceGeneratorTests(ITestOutputHelper output) : base(output, "Mono.Android", "Shiny", "Shiny.Core")
        {
        }


        // TODO: build android
        // test for finding custom shiny startup
        // test for auto-gen shiny startup
        // test with/out XF
        // test for auto-init of 3rd party
        // test for activity
        // test for permissions
        // test for partial
        // test xamessentials
        // test for xam forms auto init

        [Fact]
        public void IsAutoGeneratedStartupRegistered()
        {
            this.Generator.AddSource("[assembly: Shiny.ShinyApplicationAttribute]");
            this.RunGenerator();
            this.Compilation.SyntaxTrees.Count().Should().Be(3);
            this.Compilation
                .SyntaxTrees
                .Select(x => x.ToString())
                .Any(x => x.Contains("this.ShinyOnCreate(new AppShinyStartup());"))
                .Should()
                .BeTrue("Registration not found");
        }
    }
}
