comment: "This issue is closed because it does not meet our criteria listed in the issue template"
issueConfigs:
- content:
  - "Version of OS(s) listed above with issue"
  - "Expected Behavior"
  - "Actual Behavior"
- content:
  - "Summary"
  - "API Changes"
  - "Intended Use Case"
- content:
  - "Leave Your Message Below (don't delete this line though)"
- content:
  - "Enter Question Below (don't delete this line)"