<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <Description>Shiny Core support for Blazor PWA - connectivity and battery</Description>
        <RootNamespace>Shiny</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.JSInterop" />
    </ItemGroup>

</Project>
