<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <TargetFrameworks>$(BaseTargetFramework);$(BaseTargetFramework)-ios;$(BaseTargetFramework)-android</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('android'))">
        <PackageReference Include="Xamarin.AndroidX.AppCompat" />
    </ItemGroup>

</Project>