<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(BaseTargetFramework);$(BaseTargetFramework)-ios;$(BaseTargetFramework)-android</TargetFrameworks>
        <Description>Shiny addon for all your notification needs</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
        <ProjectReference Include="..\Shiny.Locations\Shiny.Locations.csproj" />
        <ProjectReference Include="..\Shiny.Support.Repositories\Shiny.Support.Repositories.csproj" />
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramwork.Contains('android'))">
        <PackageReference Include="Xamarin.AndroidX.AppCompat" />
    </ItemGroup>

</Project>