<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(WindowsTarget)</TargetFrameworks>

        <Description>Shiny addon for all your notification needs</Description>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)-ios</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)-maccatalyst</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)-macos</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)-android</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
        <ProjectReference Include="..\Shiny.Locations\Shiny.Locations.csproj" />
        <ProjectReference Include="..\Shiny.Support.Repositories\Shiny.Support.Repositories.csproj" />
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('android'))">
        <PackageReference Include="Xamarin.AndroidX.AppCompat" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Android" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx.Android" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState.Android" />
    </ItemGroup>

</Project>