using System;
using System.Text;

namespace Shiny.BluetoothLE.Hosting.SourceGenerators;


/// <summary>
/// Minimal indent-aware source builder.
/// </summary>
sealed class CodeWriter
{
    readonly StringBuilder builder = new();
    int indent;


    public CodeWriter Line(string text = "")
    {
        if (text.Length == 0)
        {
            this.builder.Append('\n');
            return this;
        }

        this.builder.Append(' ', this.indent * 4).Append(text).Append('\n');
        return this;
    }


    public CodeWriter Open(string text)
    {
        this.Line(text);
        this.Line("{");
        this.indent++;
        return this;
    }


    public CodeWriter Close(string suffix = "")
    {
        this.indent--;
        this.Line("}" + suffix);
        return this;
    }


    public IDisposable Block(string text)
    {
        this.Open(text);
        return new Closer(this);
    }


    /// <summary>
    /// Emits the file header every generated file carries.
    /// </summary>
    public static CodeWriter File()
    {
        var writer = new CodeWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        // generated code is not hand maintained, and consumers commonly run TreatWarningsAsErrors
        writer.Line("#pragma warning disable");
        writer.Line();
        return writer;
    }


    /// <summary>
    /// Opens the file's namespace, or returns a no-op scope for the global namespace.
    /// </summary>
    public IDisposable Namespace(string? ns)
        => String.IsNullOrEmpty(ns) ? new Closer(null) : this.Block("namespace " + ns);


    public void GeneratedCode()
        => this.Line($"[global::System.CodeDom.Compiler.GeneratedCode(\"{Names.GeneratorName}\", \"{Names.GeneratorVersion}\")]");


    public override string ToString() => this.builder.ToString();


    sealed class Closer(CodeWriter? writer) : IDisposable
    {
        public void Dispose() => writer?.Close();
    }
}
