<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(WindowsTarget)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(AndroidTarget)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(IosTarget)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(MacCatalystTarget)</TargetFrameworks>
        
        <Description>Shiny Support Library for Common Location</Description>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
    </ItemGroup>

</Project>