<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(BaseTargetFramework);$(BaseTargetFramework)-ios;$(BaseTargetFramework)-android</TargetFrameworks>
        <Description>Shiny Support Library for Common Location</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
    </ItemGroup>

</Project>