<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <Description>Shiny Data Sync for Blazor WASM via LocalStorage repository and connectivity-based draining</Description>
        <RootNamespace>Shiny.Data.Sync</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
        <ProjectReference Include="..\Shiny.Data.Sync\Shiny.Data.Sync.csproj" />
        <ProjectReference Include="..\Shiny.Core.Blazor\Shiny.Core.Blazor.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.JSInterop" />
        <PackageReference Include="Shiny.Extensions.Serialization" />
        <PackageReference Include="Shiny.Extensions.Stores.Web" />
    </ItemGroup>

</Project>
