<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <Description>Shiny Push Notifications for Blazor PWA via Web Push API</Description>
        <RootNamespace>Shiny.Push</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
        <ProjectReference Include="..\Shiny.Push\Shiny.Push.csproj" />
        <ProjectReference Include="..\Shiny.Support.Storage.Blazor\Shiny.Support.Storage.Blazor.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.JSInterop" />
    </ItemGroup>

</Project>
