<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <Description>Shiny Device Monitoring (Battery, Connectivity) for Linux via sysfs and NetworkInformation</Description>
        <RootNamespace>Shiny</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
    </ItemGroup>
</Project>
