<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
      <ProjectReference Include="..\Shiny.Support.Locations\Shiny.Support.Locations.csproj" />
      <ProjectReference Include="..\Shiny.Support.Repositories\Shiny.Support.Repositories.csproj" />
    </ItemGroup>

</Project>
