<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <Description>Shiny BluetoothLE Plugin for Blazor WebAssembly via Web Bluetooth API</Description>
        <RootNamespace>Shiny.BluetoothLE</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
        <ProjectReference Include="..\Shiny.BluetoothLE\Shiny.BluetoothLE.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.JSInterop" />
    </ItemGroup>
</Project>
