<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(StandardTargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Extensions.Configuration.Remote\Shiny.Extensions.Configuration.Remote.csproj"/>
        <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.21" />
    </ItemGroup>

</Project>
