<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(WindowsTarget)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(AndroidTarget)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(IosTarget)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(MacCatalystTarget)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(MacOsTarget)</TargetFrameworks>
        
        <Description>Shiny Reactive BluetoothLE Plugin for client/central operations</Description>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="System.Reactive" />
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
        <ProjectReference Include="..\Shiny.BluetoothLE.Common\Shiny.BluetoothLE.Common.csproj" />
        <ProjectReference Include="..\Shiny.Support.Rx\Shiny.Support.Rx.csproj" />
    </ItemGroup>
</Project>
