<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)-ios</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(TargetFrameworks);$(BaseTargetFramework)-maccatalyst</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)-android</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);$(WindowsTarget)</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <ApplicationTitle>Shiny Client</ApplicationTitle>
        <ApplicationId>org.shiny.sample</ApplicationId>
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>

        <IsAotCompatible>true</IsAotCompatible>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.19041.0</SupportedOSPlatformVersion>
        <WindowsPackageType Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">None</WindowsPackageType>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
        <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
        <PublishAot>true</PublishAot>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
        <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
        <PublishAot>true</PublishAot>
    </PropertyGroup>
    
    <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
        <CustomEntitlements Include="com.apple.security.app-sandbox" 
                            Type="Boolean" 
                            Value="true" 
                            Visible="false" />

        <CustomEntitlements Include="com.apple.security.network.client"
                            Type="Boolean"
                            Value="true"
                            Visible="false" />

        <CustomEntitlements Include="com.apple.security.network.server"
                            Type="Boolean"
                            Value="true"
                            Visible="false" />

        <CustomEntitlements Include="com.apple.security.device.bluetooth"
                            Type="Boolean"
                            Value="true"
                            Visible="false" />

        <CustomEntitlements Include="com.apple.security.personal-information.location"
                            Type="Boolean"
                            Value="true"
                            Visible="false" />

        <CustomEntitlements Include="com.apple.security.personal-information.addressbook"
                            Type="Boolean"
                            Value="true"
                            Visible="false" />

        <CustomEntitlements Include="com.apple.security.personal-information.calendars"
                            Type="Boolean"
                            Value="true"
                            Visible="false" />
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('-ios')) OR $(TargetFramework.Contains('-maccatalyst'))">
        <CustomEntitlements Include="aps-environment" Type="string" Value="development" Condition="'$(Configuration)' == 'Debug'" Visible="false" />
        <CustomEntitlements Include="aps-environment" Type="string" Value="production" Condition="'$(Configuration)' == 'Release'" Visible="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Maui.Controls"/>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Shiny.Maui.Controls" />
        <PackageReference Include="Shiny.Maui.Shell"/>
        <PackageReference Include="Microsoft.Maui.DevFlow.Agent" Condition="'$(Configuration)' == 'Debug'" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Shiny.Hosting.Maui\Shiny.Hosting.Maui.csproj" />
        <ProjectReference Include="..\..\src\Shiny.BluetoothLE\Shiny.BluetoothLE.csproj" />
        <ProjectReference Include="..\..\src\Shiny.BluetoothLE.Hosting\Shiny.BluetoothLE.Hosting.csproj" />
        <ProjectReference Include="..\..\src\Shiny.Locations\Shiny.Locations.csproj" />
        <ProjectReference Include="..\..\src\Shiny.Notifications\Shiny.Notifications.csproj" />
        <ProjectReference Include="..\..\src\Shiny.Push\Shiny.Push.csproj" />
        <ProjectReference Include="..\..\src\Shiny.Net.Http\Shiny.Net.Http.csproj" />
        <ProjectReference Include="..\..\src\Shiny.Jobs\Shiny.Jobs.csproj" />
        <ProjectReference Include="..\..\src\Shiny.Extensions.Configuration\Shiny.Extensions.Configuration.csproj" />
        <ProjectReference Include="..\Sample.Shared.Maui\Sample.Shared.Maui.csproj" />
    </ItemGroup>

</Project>
