using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Text;

namespace Shiny.AppFunctions.SourceGenerators;

/// <summary>
/// Emits the two AppFunctions assets, in the layout Jetpack androidx.appfunctions generates:
/// app_functions.xml (v1: ids) and app_functions_v2.xml (typed schema + object components).
/// Type codes follow AppFunctionDataTypeMetadata: 0 unit, 1 boolean, 3 object, 4 double, 6 long, 7 int, 8 string, 10 array, 11 reference.
/// </summary>
static class AndroidEmitter
{
    public static string EmitV1(GenerationModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>");
        sb.AppendLine("<!-- auto-generated by Shiny.AppFunctions -->");
        sb.AppendLine("<appfunctions>");
        foreach (var fn in model.Functions)
        {
            sb.AppendLine("    <appfunction>");
            sb.AppendLine($"        <function_id>{X(fn.Id)}</function_id>");
            sb.AppendLine("        <enabled_by_default>true</enabled_by_default>");
            sb.AppendLine("    </appfunction>");
        }
        sb.AppendLine("</appfunctions>");
        return sb.ToString();
    }

    public static string EmitV2(GenerationModel model)
    {
        var components = new Dictionary<string, TypeModel>();
        var sb = new StringBuilder();
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>");
        sb.AppendLine("<!-- auto-generated by Shiny.AppFunctions -->");
        sb.AppendLine("<appfunctions>");
        foreach (var fn in model.Functions)
        {
            sb.AppendLine("    <appfunction>");
            sb.AppendLine($"        <id>{X(fn.Id)}</id>");
            sb.AppendLine("        <enabledByDefault>true</enabledByDefault>");
            sb.AppendLine($"        <description>{X(fn.Description)}</description>");
            foreach (var p in fn.Parameters)
            {
                sb.AppendLine("        <parameters>");
                DataType(sb, "dataTypeMetadata", p.Type, "            ", components);
                sb.AppendLine("            <id>unused</id>");
                sb.AppendLine($"            <isRequired>{(p.IsRequired ? "true" : "false")}</isRequired>");
                sb.AppendLine($"            <name>{X(p.WireName)}</name>");
                var description = ParameterDescription(p);
                if (description != null)
                    sb.AppendLine($"            <description>{X(description)}</description>");
                sb.AppendLine("        </parameters>");
            }
            sb.AppendLine("        <response>");
            sb.AppendLine("            <id>unused</id>");
            DataType(sb, "valueType", fn.Result, "            ", components);
            sb.AppendLine("        </response>");
            sb.AppendLine($"        <functionId>{X(fn.Id)}</functionId>");
            sb.AppendLine("    </appfunction>");
        }

        if (components.Count > 0)
        {
            sb.AppendLine("    <AppFunctionComponentMetadataDocument>");
            // components can reference further components, so walk until no new ones appear
            var written = new HashSet<string>();
            while (components.Keys.Any(k => !written.Contains(k)))
            {
                foreach (var pair in components.Where(x => !written.Contains(x.Key)).ToList())
                {
                    written.Add(pair.Key);
                    var t = pair.Value;
                    sb.AppendLine("        <dataTypes>");
                    sb.AppendLine("            <dataTypeMetadata>");
                    sb.AppendLine("                <id>unused</id>");
                    sb.AppendLine("                <isNullable>false</isNullable>");
                    sb.AppendLine($"                <objectQualifiedName>{X(t.TypeName)}</objectQualifiedName>");
                    foreach (var prop in t.Properties)
                    {
                        sb.AppendLine("                <properties>");
                        DataType(sb, "dataTypeMetadata", prop.Type, "                    ", components);
                        sb.AppendLine("                    <id>unused</id>");
                        sb.AppendLine($"                    <name>{X(prop.WireName)}</name>");
                        sb.AppendLine("                </properties>");
                    }
                    foreach (var prop in t.Properties.Where(x => !x.Type.IsNullable && x.Type.IsValueType))
                        sb.AppendLine($"                <required>{X(prop.WireName)}</required>");
                    sb.AppendLine("                <type>3</type>");
                    sb.AppendLine("            </dataTypeMetadata>");
                    sb.AppendLine("            <id>unused</id>");
                    sb.AppendLine($"            <name>{X(t.TypeName)}</name>");
                    sb.AppendLine("        </dataTypes>");
                }
            }
            sb.AppendLine("        <id>unused</id>");
            sb.AppendLine("    </AppFunctionComponentMetadataDocument>");
        }
        sb.AppendLine("</appfunctions>");
        return sb.ToString();
    }

    static void DataType(StringBuilder sb, string element, TypeModel t, string indent, Dictionary<string, TypeModel> components)
    {
        sb.AppendLine($"{indent}<{element}>");
        if (t.Kind == ValueKind.Object)
        {
            components[t.TypeName] = t;
            sb.AppendLine($"{indent}    <dataTypeReference>{X(t.TypeName)}</dataTypeReference>");
        }
        sb.AppendLine($"{indent}    <id>unused</id>");
        sb.AppendLine($"{indent}    <isNullable>{(t.IsNullable ? "true" : "false")}</isNullable>");
        if (t.ItemType != null)
            DataType(sb, "itemType", t.ItemType, indent + "    ", components);
        foreach (var v in t.EnumValues)
            sb.AppendLine($"{indent}    <enumValues>{X(v)}</enumValues>");
        sb.AppendLine($"{indent}    <type>{TypeCode(t.Kind)}</type>");
        sb.AppendLine($"{indent}</{element}>");
    }

    static string? ParameterDescription(ParameterModel p)
    {
        var text = p.Description ?? p.Title;
        return p.Type.Kind switch
        {
            ValueKind.DateTimeOffset => $"{text} (ISO 8601 date and time)",
            ValueKind.Enum => $"{text} (one of: {string.Join(", ", p.Type.EnumValues)})",
            ValueKind.Entity => $"{text} (the id of a {p.Type.EntityId}; find one with search_{p.Type.EntityId})",
            _ => text
        };
    }

    static int TypeCode(ValueKind kind) => kind switch
    {
        ValueKind.Void => 0,
        ValueKind.Boolean => 1,
        ValueKind.Object => 11, // referenced; the component itself is type 3
        ValueKind.Double => 4,
        ValueKind.Int64 => 6,
        ValueKind.Int32 => 7,
        ValueKind.Array => 10,
        _ => 8 // String, DateTimeOffset, Enum, Entity (id)
    };

    static string X(string value) => SecurityElement.Escape(value) ?? "";
}
