using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Shiny.AppFunctions.SourceGenerators;

/// <summary>Emits AddAppFunctions(), the registry, and the manifest constants the build task extracts.</summary>
static class CSharpEmitter
{
    const string R = "global::Shiny.AppFunctions.";

    public static string Emit(GenerationModel model, string swift, string androidV1, string androidV2)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> by Shiny.AppFunctions");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        EmitRegistration(sb, model);
        sb.AppendLine();
        sb.AppendLine("namespace Shiny.AppFunctions.Generated");
        sb.AppendLine("{");
        EmitRegistry(sb, model);
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Read from the compiled assembly by Shiny.AppFunctions.targets; trimmed away at runtime.</summary>");
        sb.AppendLine("    internal static class __ShinyAppFunctionsManifest");
        sb.AppendLine("    {");
        sb.AppendLine($"        public const string Swift = {Verbatim(swift)};");
        sb.AppendLine($"        public const string AndroidFunctions = {Verbatim(androidV1)};");
        sb.AppendLine($"        public const string AndroidFunctionsV2 = {Verbatim(androidV2)};");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static void EmitRegistration(StringBuilder sb, GenerationModel model)
    {
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class ShinyAppFunctionsRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Registers every app function handler, entity query and delegate in this project, plus the Shiny.AppFunctions runtime.</summary>");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAppFunctions(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");
        foreach (var fn in model.Functions.Where(f => f.HandlerType != null && f.SearchesEntityId == null))
            sb.AppendLine($"            services.AddScoped<{fn.HandlerInterface}, {fn.HandlerType}>();");
        foreach (var e in model.Entities.Where(e => e.QueryType != null))
            sb.AppendLine($"            services.AddScoped<{R}IAppEntityQuery<{e.CSharpType}>, {e.QueryType}>();");
        foreach (var d in model.Delegates)
            sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(services, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped<{R}IAppFunctionDelegate, {d}>());");
        sb.AppendLine($"            {R}AppFunctionsServiceCollectionExtensions.AddAppFunctionsRuntime<global::Shiny.AppFunctions.Generated.GeneratedAppFunctionRegistry>(services);");
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    static void EmitRegistry(StringBuilder sb, GenerationModel model)
    {
        var declared = model.Functions.Where(f => f.SearchesEntityId == null).ToList();

        sb.AppendLine($"    internal sealed class GeneratedAppFunctionRegistry : {R}IAppFunctionRegistry");
        sb.AppendLine("    {");
        sb.AppendLine($"        static readonly {R}AppFunctionDescriptor[] functions = new {R}AppFunctionDescriptor[]");
        sb.AppendLine("        {");
        foreach (var fn in model.Functions)
        {
            sb.AppendLine($"            new {R}AppFunctionDescriptor");
            sb.AppendLine("            {");
            sb.AppendLine($"                Id = {Str(fn.Id)},");
            sb.AppendLine($"                Title = {Str(fn.Title)},");
            sb.AppendLine($"                Description = {Str(fn.Description)},");
            sb.AppendLine($"                OpensApp = {Bool(fn.OpensApp)},");
            if (fn.SearchesEntityId != null)
                sb.AppendLine($"                SearchesEntityId = {Str(fn.SearchesEntityId)},");
            sb.AppendLine($"                Parameters = new {R}AppParameterDescriptor[]");
            sb.AppendLine("                {");
            foreach (var p in fn.Parameters)
                sb.AppendLine($"                    new {R}AppParameterDescriptor {{ Name = {Str(p.WireName)}, Title = {Str(p.Title)}, Description = {Str(p.Description)}, IsRequired = {Bool(p.IsRequired)}, Type = {TypeDescriptor(p.Type)} }},");
            sb.AppendLine("                },");
            sb.AppendLine($"                Result = {TypeDescriptor(fn.Result)}");
            sb.AppendLine("            },");
        }
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine($"        static readonly {R}AppEntityDescriptor[] entities = new {R}AppEntityDescriptor[]");
        sb.AppendLine("        {");
        foreach (var e in model.Entities)
            sb.AppendLine($"            new {R}AppEntityDescriptor {{ Id = {Str(e.Id)}, Title = {Str(e.Title)}, TypeName = {Str(e.TypeName)} }},");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine($"        public global::System.Collections.Generic.IReadOnlyList<{R}AppFunctionDescriptor> Functions => functions;");
        sb.AppendLine($"        public global::System.Collections.Generic.IReadOnlyList<{R}AppEntityDescriptor> Entities => entities;");
        sb.AppendLine();

        // CreateRequest
        sb.AppendLine("        public async global::System.Threading.Tasks.ValueTask<object> CreateRequest(string functionId, global::System.Text.Json.JsonElement args, global::System.IServiceProvider services, global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (functionId)");
        sb.AppendLine("            {");
        foreach (var fn in declared)
        {
            sb.AppendLine($"                case {Str(fn.Id)}:");
            sb.AppendLine("                {");
            for (var i = 0; i < fn.Parameters.Count; i++)
                sb.AppendLine($"                    var p{i} = {ReadArgument(fn.Parameters[i])};");

            var ctorArgs = string.Join(", ", fn.Parameters.Select((p, i) => (p, i)).Where(x => x.p.ConstructorIndex >= 0).OrderBy(x => x.p.ConstructorIndex).Select(x => $"p{x.i}"));
            var initializers = fn.Parameters.Select((p, i) => (p, i)).Where(x => x.p.ConstructorIndex < 0).ToList();

            // an optional initializer property that was not sent keeps the value the type gives it
            var needsDefaults = initializers.Any(x => !x.p.IsRequired && !x.p.Type.IsNullable);
            if (needsDefaults)
                sb.AppendLine($"                    var defaults = new {fn.RequestType}({ctorArgs});");

            var inits = initializers.Select(x =>
                !x.p.IsRequired && !x.p.Type.IsNullable
                    ? $"{x.p.CSharpName} = p{x.i} ?? defaults.{x.p.CSharpName}"
                    : $"{x.p.CSharpName} = p{x.i}"
            ).ToList();
            var init = inits.Count == 0 ? "" : " { " + string.Join(", ", inits) + " }";
            sb.AppendLine($"                    return new {fn.RequestType}({ctorArgs}){init};");
            sb.AppendLine("                }");
        }
        sb.AppendLine("            }");
        sb.AppendLine($"            throw new {R}AppFunctionException({R}AppFunctionErrorCode.NotFound, \"Unknown function '\" + functionId + \"'\");");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Invoke
        sb.AppendLine($"        public async global::System.Threading.Tasks.Task<object?> Invoke(object request, {R}AppFunctionContext context, global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (request)");
        sb.AppendLine("            {");
        for (var i = 0; i < declared.Count; i++)
        {
            var fn = declared[i];
            var resolve = $"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{fn.HandlerInterface}>(context.Services)";
            sb.AppendLine($"                case {fn.RequestType} r{i}:");
            if (fn.Result.Kind == ValueKind.Void)
            {
                sb.AppendLine($"                    await {resolve}.Handle(r{i}, context, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine("                    return null;");
            }
            else
            {
                sb.AppendLine($"                    return await {resolve}.Handle(r{i}, context, cancellationToken).ConfigureAwait(false);");
            }
        }
        sb.AppendLine("            }");
        sb.AppendLine("            throw new global::System.InvalidOperationException(\"No app function for \" + request.GetType().FullName);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // WriteResult
        sb.AppendLine("        public void WriteResult(string functionId, object? result, global::System.Text.Json.Utf8JsonWriter writer)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (functionId)");
        sb.AppendLine("            {");
        var counter = 0;
        foreach (var fn in declared.Where(f => f.Result.Kind != ValueKind.Void))
        {
            sb.AppendLine($"                case {Str(fn.Id)}:");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var value = ({fn.Result.CSharpType})result!;");
            EmitWrite(sb, fn.Result, "value", "                    ", ref counter);
            sb.AppendLine("                    return;");
            sb.AppendLine("                }");
        }
        sb.AppendLine("            }");
        sb.AppendLine("            writer.WriteNullValue();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // QueryEntities
        sb.AppendLine($"        public async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<{R}AppEntityItem>> QueryEntities(string entityId, {R}AppEntityQueryKind kind, global::System.Collections.Generic.IReadOnlyList<string> arguments, global::System.IServiceProvider services, global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (entityId)");
        sb.AppendLine("            {");
        foreach (var e in model.Entities)
        {
            sb.AppendLine($"                case {Str(e.Id)}:");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var query = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{R}IAppEntityQuery<{e.CSharpType}>>(services);");
            sb.AppendLine("                    var found = kind switch");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        {R}AppEntityQueryKind.ByIds => await query.GetByIds(arguments, cancellationToken).ConfigureAwait(false),");
            sb.AppendLine($"                        {R}AppEntityQueryKind.Search => await query.Search(arguments.Count > 0 ? arguments[0] : \"\", cancellationToken).ConfigureAwait(false),");
            sb.AppendLine("                        _ => await query.Suggested(cancellationToken).ConfigureAwait(false)");
            sb.AppendLine("                    };");
            sb.AppendLine($"                    var items = new global::System.Collections.Generic.List<{R}AppEntityItem>(found.Count);");
            sb.AppendLine("                    foreach (var e in found)");
            sb.AppendLine($"                        items.Add(new {R}AppEntityItem(e.Id, e.{e.DisplayProperty}?.ToString() ?? e.Id));");
            sb.AppendLine("                    return items;");
            sb.AppendLine("                }");
        }
        sb.AppendLine("            }");
        sb.AppendLine($"            throw new {R}AppFunctionException({R}AppFunctionErrorCode.NotFound, \"Unknown entity '\" + entityId + \"'\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    static string ReadArgument(ParameterModel p)
    {
        var args = $"args, {Str(p.WireName)}, {Bool(p.IsRequired)}";
        var bang = p.IsRequired ? (p.Type.IsValueType ? "!.Value" : "!") : "";
        return p.Type.Kind switch
        {
            ValueKind.String => $"{R}AppFunctionArguments.GetString({args}){bang}",
            ValueKind.Int32 => $"{R}AppFunctionArguments.GetInt32({args}){bang}",
            ValueKind.Int64 => $"{R}AppFunctionArguments.GetInt64({args}){bang}",
            ValueKind.Double => $"{R}AppFunctionArguments.GetDouble({args}){bang}",
            ValueKind.Boolean => $"{R}AppFunctionArguments.GetBoolean({args}){bang}",
            ValueKind.DateTimeOffset => $"{R}AppFunctionArguments.GetDateTimeOffset({args}){bang}",
            ValueKind.Enum => $"{R}AppFunctionArguments.GetEnum<{p.Type.CSharpBaseType}>({args}){bang}",
            ValueKind.Entity => $"(await {R}AppFunctionArguments.GetEntity<{p.Type.CSharpBaseType}>({args}, services, cancellationToken).ConfigureAwait(false)){bang}",
            _ => "default!"
        };
    }

    /// <summary>Writes <paramref name="expr"/> as JSON, null-checking anything that can be null.</summary>
    static void EmitWrite(StringBuilder sb, TypeModel type, string expr, string indent, ref int counter)
    {
        var mayBeNull = !type.IsValueType || type.IsNullable;
        var v = expr;
        if (mayBeNull)
        {
            var name = "v" + counter++;
            sb.AppendLine($"{indent}if ({expr} is not {{ }} {name}) writer.WriteNullValue();");
            sb.AppendLine($"{indent}else");
            sb.AppendLine($"{indent}{{");
            v = name;
            indent += "    ";
        }

        switch (type.Kind)
        {
            case ValueKind.String:
                sb.AppendLine($"{indent}writer.WriteStringValue({v});");
                break;
            case ValueKind.Int32:
            case ValueKind.Int64:
            case ValueKind.Double:
                sb.AppendLine($"{indent}writer.WriteNumberValue({v});");
                break;
            case ValueKind.Boolean:
                sb.AppendLine($"{indent}writer.WriteBooleanValue({v});");
                break;
            case ValueKind.DateTimeOffset:
                sb.AppendLine($"{indent}{R}AppFunctionArguments.WriteDateTimeOffset(writer, {v});");
                break;
            case ValueKind.Enum:
                sb.AppendLine($"{indent}writer.WriteStringValue({v}.ToString());");
                break;
            case ValueKind.Object:
                sb.AppendLine($"{indent}writer.WriteStartObject();");
                foreach (var p in type.Properties)
                {
                    sb.AppendLine($"{indent}writer.WritePropertyName({Str(p.WireName)});");
                    EmitWrite(sb, p.Type, $"{v}.{p.CSharpName}", indent, ref counter);
                }
                sb.AppendLine($"{indent}writer.WriteEndObject();");
                break;
            case ValueKind.Array:
                var item = "item" + counter++;
                sb.AppendLine($"{indent}writer.WriteStartArray();");
                sb.AppendLine($"{indent}foreach (var {item} in {v})");
                sb.AppendLine($"{indent}{{");
                EmitWrite(sb, type.ItemType!, item, indent + "    ", ref counter);
                sb.AppendLine($"{indent}}}");
                sb.AppendLine($"{indent}writer.WriteEndArray();");
                break;
        }

        if (mayBeNull)
            sb.AppendLine($"{indent.Substring(4)}}}");
    }

    static string TypeDescriptor(TypeModel t)
    {
        var parts = new List<string>
        {
            $"Kind = {R}AppValueKind.{t.Kind}",
            $"IsNullable = {Bool(t.IsNullable)}"
        };
        if (t.TypeName.Length > 0)
            parts.Add($"TypeName = {Str(t.TypeName)}");
        if (t.EntityId != null)
            parts.Add($"EntityId = {Str(t.EntityId)}");
        if (t.EnumValues.Count > 0)
            parts.Add($"EnumValues = new string[] {{ {string.Join(", ", t.EnumValues.Select(Str))} }}");
        if (t.Properties.Count > 0)
            parts.Add($"Properties = new {R}AppPropertyDescriptor[] {{ {string.Join(", ", t.Properties.Select(p => $"new {R}AppPropertyDescriptor {{ Name = {Str(p.WireName)}, Type = {TypeDescriptor(p.Type)} }}"))} }}");
        if (t.ItemType != null)
            parts.Add($"ItemType = {TypeDescriptor(t.ItemType)}");
        return $"new {R}AppTypeDescriptor {{ {string.Join(", ", parts)} }}";
    }

    static string Bool(bool value) => value ? "true" : "false";

    public static string Str(string? value)
    {
        if (value == null)
            return "null";
        var sb = new StringBuilder("\"");
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < ' ')
                        sb.Append("\\u").Append(((int)c).ToString("x4"));
                    else
                        sb.Append(c);
                    break;
            }
        }
        return sb.Append('"').ToString();
    }

    static string Verbatim(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";
}
