using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Shiny.AppFunctions.SourceGenerators;

/// <summary>
/// Emits the App Intents Swift for the app. Everything here must stay const-extractable (literal titles, descriptions,
/// display representations and phrases), because appintentsmetadataprocessor reads them at build time.
/// The runtime half (ShinyAF.invoke and friends) ships as swift/ShinyAppFunctions.swift.
/// </summary>
static class SwiftEmitter
{
    static readonly HashSet<string> Keywords = new()
    {
        "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import", "init", "inout", "internal", "let", "open",
        "operator", "private", "precedencegroup", "protocol", "public", "rethrows", "static", "struct", "subscript", "typealias", "var",
        "break", "case", "catch", "continue", "default", "defer", "do", "else", "fallthrough", "for", "guard", "if", "in", "repeat", "return",
        "throw", "switch", "where", "while", "Any", "as", "await", "false", "is", "nil", "self", "Self", "super", "throws", "true", "try",
        "async", "some", "any", "actor", "description", "title"
    };

    public static string Emit(GenerationModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> by Shiny.AppFunctions from the app's [AppFunction] / [AppEntity] declarations.");
        sb.AppendLine("import AppIntents");
        sb.AppendLine("import Foundation");
        sb.AppendLine();

        foreach (var e in model.Enums)
            EmitEnum(sb, e);

        foreach (var e in model.Entities)
            EmitEntity(sb, e);

        foreach (var fn in model.Functions.Where(f => f.SearchesEntityId == null))
            EmitIntent(sb, fn, model);

        var shortcuts = model.Functions.Where(f => f.ShortcutPhrases.Count > 0).ToList();
        if (shortcuts.Count > 0)
        {
            sb.AppendLine("struct ShinyAppShortcuts: AppShortcutsProvider {");
            sb.AppendLine("    static var appShortcuts: [AppShortcut] {");
            foreach (var fn in shortcuts)
            {
                var phrases = string.Join(", ", fn.ShortcutPhrases.Select(Phrase));
                sb.AppendLine("        AppShortcut(");
                sb.AppendLine($"            intent: {IntentName(fn)}(),");
                sb.AppendLine($"            phrases: [{phrases}],");
                sb.AppendLine($"            shortTitle: {Str(fn.ShortcutTitle ?? fn.Title)},");
                sb.AppendLine($"            systemImageName: {Str(fn.ShortcutImage ?? "app")}");
                sb.AppendLine("        )");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }
        return sb.ToString();
    }

    static void EmitEnum(StringBuilder sb, TypeModel e)
    {
        var name = EnumName(e);
        sb.AppendLine($"enum {name}: String, AppEnum {{");
        foreach (var v in e.EnumValues)
            sb.AppendLine($"    case {Ident(Analyzer.CamelCase(v))} = {Str(v)}");
        sb.AppendLine($"    static let typeDisplayRepresentation: TypeDisplayRepresentation = {Str(Analyzer.Words(e.SimpleName))}");
        sb.AppendLine($"    static let caseDisplayRepresentations: [{name}: DisplayRepresentation] = [");
        foreach (var v in e.EnumValues)
            sb.AppendLine($"        .{Ident(Analyzer.CamelCase(v))}: {Str(Analyzer.Words(v))},");
        sb.AppendLine("    ]");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    static void EmitEntity(StringBuilder sb, EntityModel e)
    {
        var name = EntityName(e.SimpleName);
        sb.AppendLine($"struct {name}: AppEntity {{");
        sb.AppendLine($"    static let typeDisplayRepresentation: TypeDisplayRepresentation = {Str(e.Title)}");
        sb.AppendLine($"    static let defaultQuery = {name}Query()");
        sb.AppendLine("    let id: String");
        sb.AppendLine("    let displayTitle: String");
        sb.AppendLine("    var displayRepresentation: DisplayRepresentation { DisplayRepresentation(title: \"\\(displayTitle)\") }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"struct {name}Query: EntityStringQuery {{");
        sb.AppendLine($"    func entities(for identifiers: [String]) async throws -> [{name}] {{");
        sb.AppendLine($"        try await ShinyAF.entities({Str(e.Id)}, \"ids\", [\"ids\": identifiers]).map {{ {name}(id: $0.id, displayTitle: $0.title) }}");
        sb.AppendLine("    }");
        sb.AppendLine($"    func entities(matching string: String) async throws -> [{name}] {{");
        sb.AppendLine($"        try await ShinyAF.entities({Str(e.Id)}, \"search\", [\"query\": string]).map {{ {name}(id: $0.id, displayTitle: $0.title) }}");
        sb.AppendLine("    }");
        sb.AppendLine($"    func suggestedEntities() async throws -> [{name}] {{");
        sb.AppendLine($"        try await ShinyAF.entities({Str(e.Id)}, \"suggested\", [:]).map {{ {name}(id: $0.id, displayTitle: $0.title) }}");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    static void EmitIntent(StringBuilder sb, FunctionModel fn, GenerationModel model)
    {
        var name = IntentName(fn);
        sb.AppendLine($"struct {name}: AppIntent {{");
        sb.AppendLine($"    static let title: LocalizedStringResource = {Str(fn.Title)}");
        sb.AppendLine($"    static let description = IntentDescription({Str(fn.Description)})");
        sb.AppendLine($"    static let openAppWhenRun: Bool = {(fn.OpensApp ? "true" : "false")}");
        sb.AppendLine();

        foreach (var p in fn.Parameters)
        {
            var args = $"title: {Str(p.Title)}";
            if (p.Description != null)
                args += $", description: {Str(p.Description)}";
            sb.AppendLine($"    @Parameter({args})");
            sb.AppendLine($"    var {Ident(p.WireName)}: {SwiftType(p.Type)}{(p.IsRequired ? "" : "?")}");
            sb.AppendLine();
        }

        if (fn.Parameters.Count > 0)
        {
            var summary = fn.Title + " " + string.Join(" ", fn.Parameters.Where(p => p.IsRequired).Select(p => $"\\(\\.${Ident(p.WireName)})"));
            sb.AppendLine("    static var parameterSummary: some ParameterSummary {");
            sb.AppendLine($"        Summary(\"{Escape(summary.Trim())}\")");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        var (returns, value) = ResultMapping(fn.Result);
        sb.AppendLine($"    func perform() async throws -> some IntentResult{returns} & ProvidesDialog {{");
        sb.AppendLine(fn.Parameters.Count == 0 ? "        let args: [String: Any] = [:]" : "        var args: [String: Any] = [:]");
        foreach (var p in fn.Parameters)
        {
            var id = Ident(p.WireName);
            var expr = WireValue(p.Type, p.IsRequired ? id : "value");
            if (p.IsRequired)
                sb.AppendLine($"        args[{Str(p.WireName)}] = {expr}");
            else
                sb.AppendLine($"        if let value = {id} {{ args[{Str(p.WireName)}] = {expr} }}");
        }
        sb.AppendLine($"        let reply = try await ShinyAF.invoke(self, {Str(fn.Id)}, args, foreground: Self.openAppWhenRun)");
        if (value == null)
            sb.AppendLine("        return .result(dialog: reply.dialog(orDefault: \"Done\"))");
        else
            sb.AppendLine($"        return .result(value: {value}, dialog: reply.dialog(orDefault: reply.text))");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        // lets ShinyAF.invoke continue in the foreground on iOS 17-25 (iOS 26+ uses AppIntent.continueInForeground)
        sb.AppendLine($"@available(iOS 17.0, *)");
        sb.AppendLine($"extension {name}: ForegroundContinuableIntent {{}}");
        sb.AppendLine();
    }

    static (string Returns, string? Value) ResultMapping(TypeModel result) => result.Kind switch
    {
        ValueKind.Void => ("", null),
        ValueKind.Int32 or ValueKind.Int64 => (" & ReturnsValue<Int>", "reply.int"),
        ValueKind.Double => (" & ReturnsValue<Double>", "reply.double"),
        ValueKind.Boolean => (" & ReturnsValue<Bool>", "reply.bool"),
        ValueKind.DateTimeOffset => (" & ReturnsValue<Date>", "reply.date"),
        // strings and enums return their text; objects and lists return their JSON text
        _ => (" & ReturnsValue<String>", "reply.text")
    };

    static string SwiftType(TypeModel t) => t.Kind switch
    {
        ValueKind.String => "String",
        ValueKind.Int32 or ValueKind.Int64 => "Int",
        ValueKind.Double => "Double",
        ValueKind.Boolean => "Bool",
        ValueKind.DateTimeOffset => "Date",
        ValueKind.Enum => EnumName(t),
        ValueKind.Entity => EntityName(t.SimpleName),
        _ => "String"
    };

    static string WireValue(TypeModel t, string expr) => t.Kind switch
    {
        ValueKind.DateTimeOffset => $"ShinyAF.iso8601({expr})",
        ValueKind.Enum => $"{expr}.rawValue",
        ValueKind.Entity => $"{expr}.id",
        _ => expr
    };

    static string IntentName(FunctionModel fn) => Sanitize(fn.RequestSimpleName) + "Intent";
    static string EntityName(string simpleName) => Sanitize(simpleName) + "AppEntity";
    static string EnumName(TypeModel e) => Sanitize(e.SimpleName) + "AppEnum";

    static string Sanitize(string name)
    {
        var chars = name.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray();
        var s = new string(chars);
        return s.Length == 0 || char.IsDigit(s[0]) ? "_" + s : s;
    }

    static string Ident(string name) => Keywords.Contains(name) ? $"`{name}`" : name;

    /// <summary>"Create an order in ${applicationName}" → "Create an order in \(.applicationName)".</summary>
    static string Phrase(string phrase)
    {
        var parts = phrase.Split(new[] { "${applicationName}" }, System.StringSplitOptions.None);
        return "\"" + string.Join("\\(.applicationName)", parts.Select(Escape)) + "\"";
    }

    static string Str(string value) => "\"" + Escape(value) + "\"";

    /// <summary>Escapes for a Swift string literal. \( is kept only where this emitter adds interpolation itself.</summary>
    static string Escape(string value)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < value.Length; i++)
        {
            var c = value[i];
            // keep the interpolations this emitter wrote: \(\.$name)
            if (c == '\\' && i + 1 < value.Length && value[i + 1] == '(' && value.IndexOf(")", i) > i && value.Substring(i).StartsWith("\\(\\.$"))
            {
                var end = value.IndexOf(')', i);
                sb.Append(value, i, end - i + 1);
                i = end;
            }
            else
            {
                switch (c)
                {
                    case '"': sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default: sb.Append(c); break;
                }
            }
        }
        return sb.ToString();
    }
}
