<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(WindowsTarget)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(AndroidTarget)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(IosTarget)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(MacCatalystTarget)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(MacOsTarget)</TargetFrameworks>
        
        <Description>Shiny addon for all your push notification needs</Description>
    </PropertyGroup>

    <ItemGroup>
<ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('-android'))">
        <PackageReference Include="Xamarin.Firebase.Messaging"/>
    </ItemGroup>

</Project>
