<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(BaseTargetFramework);$(BaseTargetFramework)-ios;$(BaseTargetFramework)-maccatalyst;$(BaseTargetFramework)-macos;$(BaseTargetFramework)-android</TargetFrameworks>
        <TargetFrameworks Condition="'$(WindowsTarget)' != ''">$(TargetFrameworks);$(WindowsTarget)</TargetFrameworks>
        <Description>Shiny addon for all your push notification needs</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('-android'))">
        <PackageReference Include="Xamarin.Firebase.Messaging"/>
    </ItemGroup>

</Project>
