<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(BaseTargetFramework)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(AndroidTarget)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(IosTarget)</TargetFrameworks>

        <RootNamespace>Shiny.Contacts</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsAotCompatible>true</IsAotCompatible>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
        <Description>Shiny Contacts - cross-platform device contact access with CRUD and LINQ queries</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
    </ItemGroup>

</Project>
