<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <Description>Shiny Notifications for Linux via the freedesktop notifications D-Bus spec</Description>
        <RootNamespace>Shiny.Notifications</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
        <ProjectReference Include="..\Shiny.Notifications\Shiny.Notifications.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Tmds.DBus.Protocol" />
    </ItemGroup>
</Project>
