<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageVersion Include="Nerdbank.GitVersioning" Version="3.7.115" />

        <PackageVersion Include="Microsoft.Maui.Core" Version="9.0.50" />
        
        <PackageVersion Include="System.Reactive" Version="6.0.0" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
        <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.0" />

        <PackageVersion Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
        <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />

        <PackageVersion Include="Microsoft.Azure.NotificationHubs" Version="4.2.0" />

        <PackageVersion Include="sqlite-net-pcl" Version="1.9.172" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageVersion Include="Xamarin.AndroidX.Core" Version="1.12.0.1" />
        <PackageVersion Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.6.2.1" />
        <PackageVersion Include="Xamarin.AndroidX.Lifecycle.Common" Version="2.6.2.1" />

        <PackageVersion Include="Xamarin.AndroidX.AppCompat" Version="1.6.1.4" />

        <PackageVersion Include="Xamarin.GooglePlayServices.Location" Version="121.0.1.1" />

        <PackageVersion Include="Xamarin.AndroidX.Preference" Version="1.2.1.1" />
        <PackageVersion Include="Xamarin.Firebase.Messaging" Version="123.1.2.2" />

        <PackageVersion Include="Xamarin.AndroidX.Work.Runtime" Version="2.7.1.4" />
    </ItemGroup>
</Project>