<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <Description>Shiny HTTP Transfers for Blazor PWA via Service Worker Background Sync API</Description>
        <RootNamespace>Shiny.Net.Http</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
        <ProjectReference Include="..\Shiny.Net.Http\Shiny.Net.Http.csproj" />
        <ProjectReference Include="..\Shiny.Support.DeviceMonitoring.Blazor\Shiny.Support.DeviceMonitoring.Blazor.csproj" />
        <ProjectReference Include="..\Shiny.Support.Storage.Blazor\Shiny.Support.Storage.Blazor.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.JSInterop" />
    </ItemGroup>

</Project>
