<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <UserSecretsId>shiny-inapppurchases-sample</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Scalar.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Shiny.Mobile.InAppPurchases.Server\Shiny.Mobile.InAppPurchases.Server.csproj" />
    </ItemGroup>

</Project>
