name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches:
      - preview
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NugetApiKey: ${{secrets.NUGETAPIKEY}}

jobs:
  build:

    runs-on: windows-latest
#    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
          fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
          dotnet-version: '10.0.300'
          workloads: maui-ios maui-android maui-maccatalyst maui-windows macos wasm-tools

    - name: Build
      run: dotnet build Build.slnf /restore -m -property:Configuration=Release -property:PublicRelease=true

    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nugets
        path: ${{ github.workspace }}/artifacts
        retention-days: 5

    - name: Publish NuGets
      if: ${{ github.ref == 'refs/heads/preview' || startsWith(github.ref, 'refs/heads/v') }}
      run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }} --skip-duplicate